### ISSUE TITLE
无法添加插件到calibre5.1

### ISSUE THREAD

**Issue by ghost** [yingziwu/doujinshi_metadata_plugins#7]
calibre, version 5.1.0
错误： 未处理的异常: <b>ImportError</b>:cannot import name 'urlencode' from 'urllib' (C:\Program Files\Calibre2\\app\pylib.zip\urllib\__init__.pyc)

calibre 5.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: Embed Comic Metadata (1, 5, 0) && GetFileName (0, 1, 0)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 202, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "site-packages\calibre\customize\zipplugin.py", line 184, in load_module
  File "calibre_plugins.dummy1.__init__", line 16, in <module>
ImportError: cannot import name 'urlencode' from 'urllib' (C:\Program Files\Calibre2\\app\pylib.zip\urllib\__init__.pyc)

**Comment by Qinolion** [comment]
改成python3以后是这个

**Comment by ghost** [comment]
因为 from urllib 是python2的导入方式

 

  在python3中将 from urllib import urlencode 中的 “urllib” 改为 “urllib.parse” 就可以了

**Comment by ghost** [comment]
大佬更新一下吧
